version: '2'

services:
  web:
    ports:
      - 8000:8000
    volumes:
      - ./:/app:Z
      # shared volume for media
      - loyalty-media:/app/media

  db:
    ports:
      - 5432:5432

volumes:
  loyalty-media:
