version: '3'

services:
  db:
    image: postgres:14.1
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate &&
      gunicorn --bind 0.0.0.0:8000 Loyalty_Program_App.wsgi -w 3"
    volumes:
      - ./source:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/uploads

volumes:
  postgres_data:
  static_volume:
  media_volume: