version: '3'

services:
  db:
    image: postgres:14.1
    ports:
      - "5432:5432"
    env_file:
      - .env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./source:/code
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
    env_file:
      - .env.dev

  cp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./source:/code
    ports:
      - "8001:8000"
    links:
      - db
    depends_on:
      - db
      - web
    env_file:
      - .env.dev
    environment:
      - APP_ROOT_URLCONF=Loyalty_Program_App.urls_admin
      - ALLOWED_HOSTS=cp.localhost cp.allcard.me 127.0.0.1

  home:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./source:/code
    ports:
      - "8002:8000"
    links:
      - db
    depends_on:
      - db
      - web
    env_file:
      - .env.dev
    environment:
      - APP_ROOT_URLCONF=Loyalty_Program_App.urls_home
      - ALLOWED_HOSTS=localhost allcard.me 127.0.0.1

volumes:
  postgres_data: