version: '3'

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - ./mysql_data:/var/lib/mysql/
  web:
    build: .
    volumes:
      - ./source:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

