version: '3'

services:
  db:
    image: postgres:14.1
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate &&
      gunicorn --bind 0.0.0.0:8000 Loyalty_Program_App.wsgi -w 3"
    volumes:
      - ./source:/code
      - static:/home/app/web/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  bot:
    build:
      context: ./LoyaltyBot
      dockerfile: Dockerfile
    command: bash -c "python -u main.py"
    volumes:
      - ./LoyaltyBot/source:/code/bot
    depends_on:
      - web
    env_file:
      - .env

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - static:/home/app/web/static
      - ./source/uploads:/home/app/web/media

volumes:
  postgres_data:
  static: