# Generated by Django 3.2 on 2021-12-20 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('active', models.BooleanField(default=True, verbose_name='Активировать')),
                ('street', models.CharField(max_length=150, verbose_name='Улица')),
                ('building', models.CharField(max_length=20, verbose_name='Здание')),
                ('apartment', models.CharField(blank=True, max_length=20, null=True, verbose_name='Офис')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('active', models.BooleanField(default=True, verbose_name='Активировать')),
                ('code', models.CharField(max_length=150, unique=True, verbose_name='Идентификатор')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='merchantapp.address', verbose_name='Адрес')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('active', models.BooleanField(default=True, verbose_name='Активировать')),
                ('code', models.CharField(max_length=150, unique=True, verbose_name='Идентификатор')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('branch', models.ManyToManyField(related_name='branch', to='merchantapp.Branch', verbose_name='Заведение')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramConditionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('active', models.BooleanField(default=True, verbose_name='Активировать')),
                ('code', models.CharField(max_length=50, verbose_name='Идентификатор')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramRewardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('active', models.BooleanField(default=True, verbose_name='Активировать')),
                ('code', models.CharField(max_length=50, verbose_name='Идентификатор')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('active', models.BooleanField(default=True, verbose_name='Активировать')),
                ('expire_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата истечения')),
                ('redeemed', models.BooleanField(default=False, verbose_name='Выдан')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_program', to='merchantapp.program', verbose_name='Программа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reward', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('active', models.BooleanField(default=True, verbose_name='Активировать')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('reward_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='merchantapp.programrewardtype', verbose_name='Тип награды')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('active', models.BooleanField(default=True, verbose_name='Активировать')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('condition_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='merchantapp.programconditiontype', verbose_name='Тип условия')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='program',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition', to='merchantapp.programcondition', verbose_name='Условие'),
        ),
        migrations.AddField(
            model_name='program',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward', to='merchantapp.programreward', verbose_name='Награда'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('active', models.BooleanField(default=True, verbose_name='Активировать')),
                ('status', models.CharField(choices=[('RETURNED', 'Возвращён'), ('FINISHED', 'Завершён')], max_length=50, verbose_name='Статус')),
                ('completion_date', models.DateTimeField(verbose_name='Дата завершения')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_program', to='merchantapp.program', verbose_name='Программа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('active', models.BooleanField(default=True, verbose_name='Активировать')),
                ('code', models.CharField(max_length=150, unique=True, verbose_name='Идентификатор')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('category', models.CharField(choices=[('CATERING', 'Кофейни, рестораны'), ('CAR', 'Обслуживание автомобиля')], max_length=20, verbose_name='Категория')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_director', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant', to='merchantapp.merchant', verbose_name='Партнёр'),
        ),
    ]
