# Generated by Django 3.2 on 2021-12-17 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchantapp', '0003_auto_20211217_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='program_id',
            new_name='program',
        ),
    ]
