# Generated by Django 3.2 on 2022-02-14 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchantapp', '0004_auto_20220118_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='employees',
            field=models.ManyToManyField(related_name='employees', to=settings.AUTH_USER_MODEL, verbose_name='Employees'),
        ),
    ]
