# Generated by Django 3.2 on 2021-12-19 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchantapp', '0004_rename_program_id_order_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programcondition',
            old_name='size',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='programreward',
            old_name='size',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='address',
            name='apartment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='building',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=42.053456, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=65.1321, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='code',
            field=models.CharField(default=1, max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='category',
            field=models.CharField(choices=[('CATERING', 'Кофейни, рестораны'), ('CAR', 'Обслуживание автомобиля')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchant',
            name='code',
            field=models.CharField(default=1, max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchant',
            name='director',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_director', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='code',
            field=models.CharField(default=1, max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programconditiontype',
            name='code',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programrewardtype',
            name='code',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RETURNED', 'Возвращён'), ('FINISHED', 'Завершён')], max_length=50),
        ),
    ]
