# Generated by Django 3.2 on 2022-02-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchantapp', '0005_merchant_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Office'),
        ),
        migrations.AlterField(
            model_name='address',
            name='building',
            field=models.CharField(max_length=50, verbose_name='Building'),
        ),
    ]
