# Generated by Django 3.2 on 2022-02-15 06:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchantapp', '0005_merchant_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='employees',
            field=models.ManyToManyField(related_name='merchants', to=settings.AUTH_USER_MODEL, verbose_name='Employees'),
        ),
    ]
