# Generated by Django 3.2 on 2021-12-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211223_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tg_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
