# Generated by Django 3.2 on 2022-01-18 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='DateOfBirth'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(help_text='HelpTextPhone', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='PhoneValidatorMessage', regex='^7?\\d{10}')], verbose_name='PhoneNumber'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tg_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='TelegramID'),
        ),
    ]
