name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: docker-compose up --build
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: docker run --network container:web -s --retry 10 --retry-connrefused http://cabinet.allcard.me/
